function app1
fh=figure('units','pixels',........
    'position',[150 350 600 600],...
    'color',[163/255 73/255 164/255],...
    'name','Myapp');
ui1=uicontrol('parent',fh,...
    'units','pixels',...
    'position',[450 450 100 100],...
    'style','pushbutton',...
    'string','increment',...
    'callback',@tap);
ui2=uicontrol('parent',fh,...
    'units','pixels',...
    'position',[250 350 100 100],...
    'style','text',...
    'string','Mygui');
ui3=uicontrol('parent',fh,...
    'units','pixels',...
    'position',[450 350 100 100],...
    'style','pushbutton',...
    'string','multiply',...
 'callback',@tip);
count=0;
    function tap(hobject,evendata)
        count=count+1;
      %  disp(count);
      set (ui2,'string',num2str(count))
    end
function tip(hobject,evendata)
        count=count*2;
      %  disp(count);
      set (ui2,'string',num2str(count))
    end
end
